'use client'

import { useEffect, useRef, useState } from 'react'
import { use } from 'react'
import { useRouter } from 'next/navigation'
import { motion, AnimatePresence } from 'framer-motion'
import {
  ChevronRight, RefreshCw, BarChart3, BarChart2,
  GitBranch, Trophy, AlertTriangle, CheckCircle2, Loader2, PlusCircle,
  SlidersHorizontal, Sparkles, FileText, Clock, Upload, Trash2,
} from 'lucide-react'
import toast from 'react-hot-toast'
import {
  api,
  type Project, type Idea, type IdeaGraphResponse,
  type Evaluation, type ProjectStatus, type Report,
} from '@/lib/api'
import { useProjectStatus, STATUS_LABELS, STATUS_ORDER } from '@/hooks/useProjectStatus'
import { StatusBadge } from '@/components/project/StatusBadge'
import { IdeaCard } from '@/components/project/IdeaCard'
import { IdeaGraph } from '@/components/project/IdeaGraph'
import { CouncilPanel } from '@/components/project/CouncilPanel'
import { AnalyticsPanel } from '@/components/project/AnalyticsPanel'
import { AddIdeaModal } from '@/components/project/AddIdeaModal'
import { ReportView } from '@/components/project/ReportView'
import { formatDate, formatRelative } from '@/lib/utils'

type Tab = 'overview' | 'ideas' | 'analytics' | 'graph' | 'report' | 'history'

const TABS: { key: Tab; label: string; icon: typeof BarChart3 }[] = [
  { key: 'overview',  label: 'Overview',  icon: BarChart3  },
  { key: 'ideas',     label: 'Ideas',     icon: Trophy     },
  { key: 'analytics', label: 'Analytics', icon: BarChart2  },
  { key: 'graph',     label: 'Graph',     icon: GitBranch  },
  { key: 'report',    label: 'Report',    icon: FileText   },
  { key: 'history',   label: 'History',   icon: Clock      },
]

/* ── Status timeline ──────────────────────────────────────────────────────── */

function StatusTimeline({ status }: { status: ProjectStatus }) {
  const currentIdx = STATUS_ORDER.indexOf(status)

  return (
    <div className="flex items-center gap-0 overflow-x-auto pb-2">
      {STATUS_ORDER.filter(s => s !== 'FAILED').map((s, i) => {
        const isCompleted = status === 'COMPLETED'
        const done   = i < currentIdx || isCompleted
        const active = i === currentIdx && !isCompleted
        const last   = i === STATUS_ORDER.length - 2

        return (
          <div key={s} className="flex items-center shrink-0">
            <div className="flex flex-col items-center gap-1">
              <div className={`
                w-7 h-7 rounded-full border-2 flex items-center justify-center text-[10px] font-bold transition-all duration-500
                ${done   ? 'border-[var(--accent)] bg-[var(--accent)] text-white' : ''}
                ${active ? 'border-[var(--accent)] bg-transparent text-[var(--accent)] animate-pulse' : ''}
                ${!done && !active ? 'border-[var(--border)] bg-transparent text-[var(--muted)]' : ''}
              `}>
                {done ? <CheckCircle2 className="w-3.5 h-3.5" /> : active ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : i + 1}
              </div>
              <span className={`text-[9px] whitespace-nowrap ${active ? 'text-[var(--accent)]' : done ? 'text-[var(--muted)]' : 'text-[var(--border)]'}`}>
                {STATUS_LABELS[s]}
              </span>
            </div>
            {!last && (
              <div className={`w-8 sm:w-14 h-px mx-1 transition-colors duration-500 shrink-0 ${i < currentIdx ? 'bg-[var(--accent)]' : 'bg-[var(--border)]'}`} />
            )}
          </div>
        )
      })}
    </div>
  )
}

/* ── History helpers ──────────────────────────────────────────────────────── */

type HistoryEvent = {
  id: string
  at: Date
  emoji: string
  title: string
  desc: string
  color: string
}

function buildHistory(
  project: Project,
  ideas: Idea[],
  evaluations: Evaluation[],
  report: Report | null,
): HistoryEvent[] {
  const events: HistoryEvent[] = []

  events.push({
    id: 'created',
    at: new Date(project.created_at),
    emoji: '🚀',
    title: 'Project created',
    desc: project.title,
    color: '#6366f1',
  })

  const aiIdeas = ideas.filter(i => i.generator_type !== null && i.version === 1)
  if (aiIdeas.length > 0) {
    const first = aiIdeas.reduce((a, b) => a.created_at < b.created_at ? a : b)
    const gens = [...new Set(aiIdeas.map(i => i.generator_type))].join(', ')
    events.push({
      id: 'generated',
      at: new Date(first.created_at),
      emoji: '💡',
      title: `${aiIdeas.length} ideas generated by AI`,
      desc: gens,
      color: '#7c3aed',
    })
  }

  const userIdeas = ideas.filter(i => i.generator_type === null)
  userIdeas.forEach(idea => {
    events.push({
      id: `user_${idea.id}`,
      at: new Date(idea.created_at),
      emoji: '✍️',
      title: 'You added an idea',
      desc: idea.title,
      color: '#db2777',
    })
  })

  if (evaluations.length > 0) {
    const first = evaluations.reduce((a, b) => a.created_at < b.created_at ? a : b)
    events.push({
      id: 'judged',
      at: new Date(first.created_at),
      emoji: '⚖️',
      title: 'Council completed judging',
      desc: `${evaluations.length} evaluations across all judges`,
      color: '#d97706',
    })
  }

  const evolvedIdeas = ideas.filter(i => i.version > 1 && i.parent_idea_id !== null)
  if (evolvedIdeas.length > 0) {
    const first = evolvedIdeas.reduce((a, b) => a.created_at < b.created_at ? a : b)
    events.push({
      id: 'evolved',
      at: new Date(first.created_at),
      emoji: '🧬',
      title: `${evolvedIdeas.length} ideas evolved`,
      desc: 'AI improved ideas using judge feedback',
      color: '#059669',
    })
  }

  if (report) {
    events.push({
      id: 'report',
      at: new Date(report.created_at),
      emoji: '📋',
      title: 'Execution report generated',
      desc: 'Winning idea roadmap complete',
      color: '#eab308',
    })
  }

  return events.sort((a, b) => b.at.getTime() - a.at.getTime())
}

/* ── Page ─────────────────────────────────────────────────────────────────── */

export default function ProjectPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params)
  const router = useRouter()

  const [initial, setInitial]           = useState<Project | null>(null)
  const [tab, setTab]                   = useState<Tab>('overview')

  const [ideas, setIdeas]               = useState<Idea[]>([])
  const [graph, setGraph]               = useState<IdeaGraphResponse | null>(null)
  const [evaluations, setEvaluations]   = useState<Evaluation[]>([])
  const [report, setReport]             = useState<Report | null>(null)
  const [loading, setLoading]           = useState(true)

  const [addIdeaOpen, setAddIdeaOpen]   = useState(false)
  const [constraintsOpen, setConstraintsOpen] = useState(false)
  const [constraints, setConstraints]   = useState('')
  const [generating, setGenerating]     = useState(false)

  const [docFile, setDocFile]           = useState<File | null>(null)
  const [docUploading, setDocUploading] = useState(false)
  const docInputRef                     = useRef<HTMLInputElement>(null)

  const [resetting, setResetting]       = useState(false)
  const [confirmReset, setConfirmReset] = useState(false)

  // Initial load
  useEffect(() => {
    api.projects.get(id)
      .then(p => setInitial(p))
      .catch(() => { toast.error('Project not found'); router.push('/projects') })
      .finally(() => setLoading(false))
  }, [id])

  // Live polling
  const { project: live } = useProjectStatus(id, initial?.status ?? 'CREATED')
  const project = live ?? initial

  // Load ideas/graph/evaluations/report when completed or in-progress
  useEffect(() => {
    if (!project) return
    if (project.status === 'COMPLETED' || project.status === 'FAILED') {
      Promise.all([
        api.projects.ideas(id).catch(() => [] as Idea[]),
        api.projects.graph(id).catch(() => null),
        api.projects.evaluations(id).catch(() => [] as Evaluation[]),
        api.projects.report(id).catch(() => null),
      ]).then(([i, g, e, r]) => {
        setIdeas(i)
        setGraph(g)
        setEvaluations(e)
        setReport(r)
      }).catch(() => toast.error('Failed to load project results'))
    } else if (['JUDGING', 'EVOLVING', 'TOURNAMENT', 'REPORTING'].includes(project.status)) {
      api.projects.ideas(id).then(setIdeas).catch(() => null)
    }
  }, [project?.status, id])

  async function rerun() {
    if (!project) return
    try {
      await api.projects.run(id)
      toast.success('Workflow restarted.')
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Failed to restart')
    }
  }

  async function handleEvolve(ideaId: string): Promise<Idea[]> {
    try {
      const newIdeas = await api.projects.evolveIdea(id, ideaId)
      setIdeas(prev => [...prev, ...newIdeas])
      toast.success(`${newIdeas.length} evolved idea${newIdeas.length !== 1 ? 's' : ''} added — judged by all 3 critics`)
      Promise.all([
        api.projects.graph(id).catch(() => null),
        api.projects.evaluations(id).catch(() => [] as Evaluation[]),
      ]).then(([g, e]) => {
        if (g) setGraph(g)
        if (e.length > 0) setEvaluations(e)
      })
      return newIdeas
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Evolution failed')
      return []
    }
  }

  async function handleGenerateWithConstraints() {
    if (!constraints.trim() || generating) return
    setGenerating(true)
    try {
      const newIdeas = await api.projects.generateWithConstraints(id, constraints.trim())
      setIdeas(prev => [...prev, ...newIdeas])
      toast.success(`${newIdeas.length} new ideas generated from your constraints`)
      setConstraints('')
      setConstraintsOpen(false)
      Promise.all([
        api.projects.graph(id).catch(() => null),
        api.projects.evaluations(id).catch(() => [] as Evaluation[]),
      ]).then(([g, e]) => {
        if (g) setGraph(g)
        if (e.length > 0) setEvaluations(e)
      })
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Generation failed')
    } finally {
      setGenerating(false)
    }
  }

  async function handleDocUpload() {
    if (!docFile || docUploading) return
    setDocUploading(true)
    try {
      const res = await api.projects.uploadDocument(id, docFile)
      toast.success(`Uploaded ${res.filename} — ${res.chunk_count} chunks indexed`)
      setDocFile(null)
      if (docInputRef.current) docInputRef.current.value = ''
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Upload failed')
    } finally {
      setDocUploading(false)
    }
  }

  async function handleReset() {
    setResetting(true)
    try {
      await api.projects.reset(id)
      setIdeas([])
      setGraph(null)
      setEvaluations([])
      setReport(null)
      setConfirmReset(false)
      setTab('overview')
      toast.success('History cleared — project reset to start')
      // Refresh project status
      const updated = await api.projects.get(id)
      setInitial(updated)
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Reset failed')
    } finally {
      setResetting(false)
    }
  }

  if (loading || !project) {
    return (
      <div className="flex items-center justify-center min-h-[50vh]">
        <Loader2 className="w-8 h-8 text-[var(--accent)] animate-spin" />
      </div>
    )
  }

  const isRunning = !['CREATED', 'COMPLETED', 'FAILED'].includes(project.status)
  const isFailed  = project.status === 'FAILED'
  const isDone    = project.status === 'COMPLETED'
  const winner    = ideas.find(i => i.is_winner)
  const graphHasData = graph != null && graph.nodes.length > 0

  const historyEvents = buildHistory(project, ideas, evaluations, report)

  return (
    <div className="space-y-8">
      {/* Breadcrumb */}
      <div className="flex items-center gap-2 text-[var(--muted)] text-xs">
        <span className="hover:text-white cursor-pointer" onClick={() => router.push('/projects')}>Projects</span>
        <ChevronRight className="w-3 h-3" />
        <span className="text-white truncate max-w-xs">{project.title}</span>
      </div>

      {/* Header card */}
      <motion.div
        initial={{ opacity: 0, y: -12 }}
        animate={{ opacity: 1, y: 0 }}
        className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"
      >
        <div className="flex items-start gap-4 justify-between flex-wrap">
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-3 mb-2 flex-wrap">
              <h1 className="text-xl font-bold text-white font-serif truncate">{project.title}</h1>
              <StatusBadge status={project.status} />
            </div>
            <p className="text-[var(--muted)] text-sm line-clamp-2 leading-relaxed mb-1">
              {project.problem_statement}
            </p>
            <p className="text-[10px] text-[var(--muted)]/60">Created {formatDate(project.created_at)}</p>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            {isFailed && (
              <button
                onClick={rerun}
                className="flex items-center gap-2 px-4 py-2 border border-[var(--border)] text-sm text-[var(--muted)] hover:text-white hover:border-[var(--accent)] rounded-lg transition-colors"
              >
                <RefreshCw className="w-4 h-4" />
                Retry
              </button>
            )}
            {!confirmReset ? (
              <button
                onClick={() => setConfirmReset(true)}
                disabled={ideas.length === 0 && !report}
                title="Delete all ideas, evaluations and report"
                className="flex items-center gap-1.5 px-3 py-2 border border-red-800/40 text-red-500 text-xs rounded-lg hover:border-red-600 hover:bg-red-950/30 disabled:opacity-25 disabled:cursor-not-allowed transition-colors"
              >
                <Trash2 className="w-3.5 h-3.5" />
                Clean
              </button>
            ) : (
              <div className="flex items-center gap-2">
                <span className="text-xs text-red-400 hidden sm:block">Reset project?</span>
                <button
                  onClick={handleReset}
                  disabled={resetting}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-red-700 hover:bg-red-600 text-white text-xs font-medium disabled:opacity-60 transition-colors"
                >
                  {resetting ? <Loader2 className="w-3 h-3 animate-spin" /> : <Trash2 className="w-3 h-3" />}
                  Confirm
                </button>
                <button
                  onClick={() => setConfirmReset(false)}
                  disabled={resetting}
                  className="px-3 py-1.5 rounded-lg border border-[var(--border)] text-xs text-[var(--muted)] hover:text-white transition-colors"
                >
                  Cancel
                </button>
              </div>
            )}
          </div>
        </div>

        {!isFailed && (
          <div className="mt-6 pt-5 border-t border-[var(--border)]">
            <StatusTimeline status={project.status} />
          </div>
        )}

        {isFailed && (
          <div className="mt-4 flex items-center gap-2 text-red-400 text-xs">
            <AlertTriangle className="w-4 h-4" />
            The workflow encountered an error. You can retry from the beginning.
          </div>
        )}

        {isDone && winner && (
          <div className="mt-4 flex items-center gap-2 text-yellow-400 text-xs">
            <Trophy className="w-4 h-4" />
            Winning idea: <span className="font-semibold text-white">{winner.title}</span>
            {winner.score != null && <span>· Score: {winner.score.toFixed(1)}/10</span>}
          </div>
        )}
      </motion.div>

      {/* Tabs */}
      <div className="flex gap-1 border-b border-[var(--border)] overflow-x-auto">
        {TABS.map(({ key, label, icon: Icon }) => {
          const active = tab === key
          const disabled =
            (key === 'analytics' && ideas.length === 0) ||
            (key === 'graph'     && !graphHasData)      ||
            (key === 'ideas'     && ideas.length === 0) ||
            (key === 'report'    && !report)

          return (
            <button
              key={key}
              onClick={() => !disabled && setTab(key)}
              disabled={disabled}
              className={`
                flex items-center gap-2 px-4 py-2.5 text-xs font-medium border-b-2 transition-all whitespace-nowrap
                ${active
                  ? 'border-[var(--accent)] text-[var(--accent)]'
                  : disabled
                    ? 'border-transparent text-[var(--border)] cursor-not-allowed'
                    : 'border-transparent text-[var(--muted)] hover:text-[var(--text)]'
                }
              `}
            >
              <Icon className="w-3.5 h-3.5" />
              {label}
              {key === 'ideas' && ideas.length > 0 && (
                <span className="px-1.5 py-0.5 bg-[var(--elevated)] rounded text-[9px]">{ideas.length}</span>
              )}
            </button>
          )
        })}
      </div>

      {/* Tab content */}
      <AnimatePresence mode="wait">
        <motion.div
          key={tab}
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -8 }}
          transition={{ duration: 0.25 }}
        >
          {/* ── Overview ─────────────────────────────────────────────────── */}
          {tab === 'overview' && (
            <div className="space-y-6">
              {isRunning && (
                <div className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-6">
                  <div className="flex items-center gap-3 mb-4">
                    <Loader2 className="w-5 h-5 text-[var(--accent)] animate-spin" />
                    <h3 className="font-semibold text-white">Workflow in progress</h3>
                  </div>
                  <p className="text-[var(--muted)] text-sm leading-relaxed">
                    {STATUS_LABELS[project.status]}… The Council is deliberating.
                    This page updates automatically every few seconds.
                  </p>
                  <motion.div className="mt-4 h-1 bg-[var(--elevated)] rounded-full overflow-hidden">
                    <motion.div
                      className="h-full bg-[var(--accent)] rounded-full"
                      animate={{ x: ['-100%', '200%'] }}
                      transition={{ duration: 1.8, repeat: Infinity, ease: 'easeInOut' }}
                    />
                  </motion.div>
                </div>
              )}

              {isDone && (
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                  <StatCard label="Ideas Generated" value={ideas.length.toString()} icon="💡" />
                  <StatCard
                    label="Winner Score"
                    value={winner?.score != null ? `${winner.score.toFixed(1)}/10` : '—'}
                    icon="🏆"
                  />
                  <StatCard
                    label="Evolved Ideas"
                    value={ideas.filter(i => i.version > 1).length.toString()}
                    icon="🧬"
                  />
                </div>
              )}

              {!['CREATED'].includes(project.status) && (
                <CouncilPanel
                  ideas={ideas}
                  evaluationEdges={graph?.evaluation_edges ?? []}
                  isRunning={isRunning}
                />
              )}

              <div className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-6">
                <h3 className="font-semibold text-white mb-3 text-sm">Problem Statement</h3>
                <p className="text-[var(--muted)] text-sm leading-relaxed whitespace-pre-wrap">
                  {project.problem_statement}
                </p>
              </div>

              {/* Document Upload */}
              <div className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-6">
                <h3 className="font-semibold text-white mb-1 text-sm flex items-center gap-2">
                  <Upload className="w-4 h-4 text-[var(--muted)]" />
                  Upload Context Document
                </h3>
                <p className="text-xs text-[var(--muted)] mb-4 leading-relaxed">
                  Upload a PDF, text, or markdown file. The AI generators will use it as additional context when creating ideas.
                </p>
                <div className="flex items-center gap-3 flex-wrap">
                  <label className="flex items-center gap-2 px-4 py-2 rounded-lg border border-dashed border-[var(--border)] text-xs text-[var(--muted)] hover:border-[var(--accent)] hover:text-white cursor-pointer transition-colors">
                    <Upload className="w-3.5 h-3.5" />
                    {docFile ? docFile.name : 'Choose file'}
                    <input
                      ref={docInputRef}
                      type="file"
                      accept=".pdf,.txt,.md,.markdown"
                      className="hidden"
                      onChange={e => setDocFile(e.target.files?.[0] ?? null)}
                    />
                  </label>
                  {docFile && (
                    <button
                      onClick={handleDocUpload}
                      disabled={docUploading}
                      className="flex items-center gap-2 px-4 py-2 rounded-lg bg-[var(--accent)] text-white text-xs font-medium hover:opacity-90 disabled:opacity-50 transition-opacity"
                    >
                      {docUploading
                        ? <><Loader2 className="w-3.5 h-3.5 animate-spin" /> Uploading…</>
                        : 'Upload'
                      }
                    </button>
                  )}
                </div>
              </div>
            </div>
          )}

          {/* ── Ideas ────────────────────────────────────────────────────── */}
          {tab === 'ideas' && (
            <div className="space-y-6">
              {winner && (
                <div className="rounded-xl border border-yellow-500/30 bg-yellow-950/10 p-4 flex items-start gap-3">
                  <Trophy className="w-5 h-5 text-yellow-400 shrink-0 mt-0.5" />
                  <div>
                    <p className="text-yellow-300 font-semibold text-sm">{winner.title}</p>
                    <p className="text-yellow-400/60 text-xs mt-1">{winner.solution}</p>
                  </div>
                </div>
              )}

              {isDone && (
                <div className="flex items-center gap-3 flex-wrap">
                  <button
                    onClick={() => setConstraintsOpen(v => !v)}
                    className={`flex items-center gap-2 px-4 py-2 rounded-lg border text-sm transition-colors ${
                      constraintsOpen
                        ? 'border-violet-500 bg-violet-900/30 text-violet-300'
                        : 'border-violet-700/50 bg-violet-900/10 text-violet-400 hover:border-violet-500 hover:bg-violet-900/20'
                    }`}
                  >
                    <SlidersHorizontal className="w-4 h-4" />
                    Generate with Constraints
                  </button>
                  <button
                    onClick={() => setAddIdeaOpen(true)}
                    className="flex items-center gap-2 px-4 py-2 rounded-lg border border-pink-700/50 bg-pink-900/20 text-pink-300 text-sm hover:border-pink-500 hover:bg-pink-900/40 transition-colors"
                  >
                    <PlusCircle className="w-4 h-4" />
                    Add Your Idea
                  </button>
                </div>
              )}

              {constraintsOpen && (
                <motion.div
                  initial={{ opacity: 0, y: -8 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="rounded-xl border border-violet-700/40 bg-violet-950/20 p-5 space-y-4"
                >
                  <div>
                    <h3 className="text-sm font-semibold text-white mb-1 flex items-center gap-2">
                      <Sparkles className="w-4 h-4 text-violet-400" />
                      Generate Ideas with Your Constraints
                    </h3>
                    <p className="text-xs text-[var(--muted)] leading-relaxed">
                      Narrow the problem space. All 4 AI generators will produce new ideas
                      respecting your requirements, each judged by the full council.
                    </p>
                  </div>
                  <textarea
                    value={constraints}
                    onChange={e => setConstraints(e.target.value)}
                    placeholder={`Examples:\n• Budget under ₹5 lakhs to build MVP\n• Must work offline in rural areas with 2G connectivity\n• Target college students aged 18-22 in Tier-2 cities\n• No blockchain, no NFTs\n• Must integrate with UPI and Aadhaar`}
                    rows={5}
                    className="w-full rounded-lg border border-[var(--border)] bg-[var(--surface)] text-sm text-[var(--text)] placeholder:text-[var(--muted)]/50 px-4 py-3 resize-none focus:outline-none focus:border-violet-500 transition-colors"
                  />
                  <div className="flex items-center gap-3">
                    <button
                      onClick={handleGenerateWithConstraints}
                      disabled={!constraints.trim() || generating}
                      className={`flex items-center gap-2 px-5 py-2.5 rounded-lg text-sm font-medium transition-all ${
                        !constraints.trim() || generating
                          ? 'bg-violet-900/30 text-violet-600 cursor-not-allowed border border-violet-900/40'
                          : 'bg-violet-600 hover:bg-violet-500 text-white border border-violet-500'
                      }`}
                    >
                      {generating
                        ? <><Loader2 className="w-4 h-4 animate-spin" /> Generating — all 4 AI agents working (~30s)…</>
                        : <><Sparkles className="w-4 h-4" /> Generate Ideas</>
                      }
                    </button>
                    <span className="text-[10px] text-[var(--muted)]">
                      Generates ~8 new ideas, each judged by 3 critics
                    </span>
                  </div>
                </motion.div>
              )}

              <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
                {[...ideas]
                  .sort((a, b) => (b.score ?? 0) - (a.score ?? 0))
                  .map((idea, i) => (
                    <IdeaCard
                      key={idea.id}
                      idea={idea}
                      index={i}
                      evaluations={evaluations}
                      onEvolve={isDone ? () => handleEvolve(idea.id) : undefined}
                    />
                  ))
                }
              </div>
            </div>
          )}

          {/* ── Analytics ────────────────────────────────────────────────── */}
          {tab === 'analytics' && (
            <AnalyticsPanel ideas={ideas} graph={graph} evaluations={evaluations} />
          )}

          {/* ── Graph ────────────────────────────────────────────────────── */}
          {tab === 'graph' && graph && (
            <div className="space-y-4">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <h2 className="text-lg font-semibold text-white font-serif mb-1">Idea Lineage Graph</h2>
                  <p className="text-xs text-[var(--muted)]">
                    Every idea and its evolution chain, auto-scaled to fit.
                    Click any node to inspect judge scores and evolution rationale.
                  </p>
                </div>
                <button
                  onClick={() => {
                    Promise.all([
                      api.projects.graph(id).catch(() => null),
                      api.projects.evaluations(id).catch(() => [] as Evaluation[]),
                    ]).then(([g, e]) => {
                      if (g) setGraph(g)
                      if (e && e.length > 0) setEvaluations(e)
                      toast.success('Graph refreshed')
                    })
                  }}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-[var(--border)] text-xs text-[var(--muted)] hover:text-white hover:border-[var(--accent)] transition-colors shrink-0"
                >
                  <RefreshCw className="w-3 h-3" />
                  Refresh
                </button>
              </div>
              <IdeaGraph graph={graph} />
            </div>
          )}

          {/* ── Report ───────────────────────────────────────────────────── */}
          {tab === 'report' && report && (
            <ReportView report={report} />
          )}

          {/* ── History ──────────────────────────────────────────────────── */}
          {tab === 'history' && (
            <div className="space-y-6">
              <div>
                <h2 className="text-lg font-semibold text-white font-serif">Activity History</h2>
                <p className="text-xs text-[var(--muted)] mt-0.5">Timeline of everything that happened in this project</p>
              </div>

              {/* Timeline */}
              <div className="relative space-y-0">
                {historyEvents.length === 0 ? (
                  <p className="text-[var(--muted)] text-sm">No activity yet. Run the workflow to get started.</p>
                ) : (
                  historyEvents.map((ev, idx) => (
                    <div key={ev.id} className="flex gap-4">
                      {/* connector */}
                      <div className="flex flex-col items-center">
                        <div
                          className="w-8 h-8 rounded-full flex items-center justify-center text-sm shrink-0 border"
                          style={{ borderColor: ev.color + '55', background: ev.color + '18' }}
                        >
                          {ev.emoji}
                        </div>
                        {idx < historyEvents.length - 1 && (
                          <div className="w-px flex-1 bg-[var(--border)] my-1" style={{ minHeight: 24 }} />
                        )}
                      </div>
                      {/* content */}
                      <div className="pb-6 pt-1 flex-1 min-w-0">
                        <p className="text-sm font-medium text-white">{ev.title}</p>
                        <p className="text-xs text-[var(--muted)] mt-0.5 truncate">{ev.desc}</p>
                        <p className="text-[10px] text-[var(--muted)]/50 mt-1">{formatRelative(ev.at.toISOString())} · {formatDate(ev.at.toISOString())}</p>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          )}
        </motion.div>
      </AnimatePresence>

      <AddIdeaModal
        projectId={id}
        open={addIdeaOpen}
        onClose={() => setAddIdeaOpen(false)}
        onAdded={idea => {
          setIdeas(prev => [...prev, idea])
          Promise.all([
            api.projects.graph(id).catch(() => null),
            api.projects.evaluations(id).catch(() => [] as Evaluation[]),
          ]).then(([g, e]) => {
            if (g) setGraph(g)
            if (e.length > 0) setEvaluations(e)
          })
        }}
      />
    </div>
  )
}

function StatCard({ label, value, icon }: { label: string; value: string; icon: string }) {
  return (
    <div className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-5">
      <div className="text-2xl mb-2">{icon}</div>
      <div className="text-2xl font-bold text-white mb-1">{value}</div>
      <div className="text-xs text-[var(--muted)]">{label}</div>
    </div>
  )
}
